name: indoor_navigation
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_tts: 1.2.7

  video_player: ^0.11.1+4

  qrscan: 0.2.17

  google_sign_in: ^4.5.3

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/direction.mp4
  uses-material-design: true
